
export default {

    'MeshBasicMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'color': true,
        'combine': true,
        'envMap': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'lights': true,
        'map': true,
        'morphTargets': true,
        'reflectivity': true,
        'combine': true,
        'refractionRatio': true,
        'skinning': true,
        'specularMap': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true

    },

    'MeshLambertMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'color': true,
        'combine': true,
        'emissive': true,
        'emissiveMap': true,
        'emissiveIntensity': true,
        'envMap': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'map': true,
        'morphNormals': true,
        'morphTargets': true,
        'reflectivity': true,
        'combine': true,
        'refractionRatio': true,
        'skinning': true,
        'specularMap': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true
    },

    'MeshPhongMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'bumpMap': true,
        'bumpScale': true,
        'color': true,
        'combine': true,
        'displacementMap': true,
        'displacementScale': true,
        'displacementBias': true,
        'emissive': true,
        'emissiveMap': true,
        'emissiveIntensity': true,
        'envMap': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'map': true,
        'morphNormals': true,
        'morphTargets': true,
        'normalMap': true,
        'normalScale': true,
        'reflectivity': true,
        'combine': true,
        'refractionRatio': true,
        'shininess': true,
        'skinning': true,
        'specular': true,
        'specularMap': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true
    },

    'MeshStandardMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'bumpMap': true,
        'bumpScale': true,
        'color': true,
        'displacementMap': true,
        'displacementScale': true,
        'displacementBias': true,
        'emissive': true,
        'emissiveMap': true,
        'emissiveIntensity': true,
        'envMap': true,
        'envMapIntensity': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'map': true,
        'metalness': true,
        'metalnessMap': true,
        'morphNormals': true,
        'morphTargets': true,
        'normalMap': true,
        'normalScale': true,
        'refractionRatio': true,
        'roughness': true,
        'roughnessMap': true,
        'skinning': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true

    },

    'MeshPhysicalMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'bumpMap': true,
        'bumpScale': true,
        'color': true,
        'displacementMap': true,
        'displacementScale': true,
        'displacementBias': true,
        'emissive': true,
        'emissiveMap': true,
        'emissiveIntensity': true,
        'envMap': true,
        'envMapIntensity': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'map': true,
        'metalness': true,
        'metalnessMap': true,
        'morphNormals': true,
        'morphTargets': true,
        'normalMap': true,
        'normalScale': true,
        'refractionRatio': true,
        'roughness': true,
        'roughnessMap': true,
        'skinning': true,
        'clearCoat': true,
        'clearCoatRoughness': true,
        'reflectivity': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true
    },

    'MeshToonMaterial': {

        'alphaMap': true,
        'aoMap': true,
        'aoMapIntensity': true,
        'bumpMap': true,
        'bumpScale': true,
        'color': true,
        'combine': true,
        'displacementMap': true,
        'displacementScale': true,
        'displacementBias': true,
        'emissive': true,
        'emissiveMap': true,
        'emissiveIntensity': true,
        'envMap': true,
        'lightMap': true,
        'lightMapIntensity': true,
        'map': true,
        'morphNormals': true,
        'morphTargets': true,
        'normalMap': true,
        'normalScale': true,
        'reflectivity': true,
        'combine': true,
        'refractionRatio': true,
        'shininess': true,
        'skinning': true,
        'specular': true,
        'specularMap': true,
        'gradientMap': true,
        'xrep': true,
        'yrep': true,
        'xoff': true,
        'yoff': true
    },

    'ShaderMaterial': {

        'clipping': true,
        'defaultAttributeValues': true,
        'extensions': true,
        'fog': true,
        'fragmentShader': true,
        'index0AttributeName': true,
        'lights': true,
        'morphTargets': true,
        'morphNormals': true,
        'shading': true,
        'skinning': true,
        'uniforms': true,
        'vertexColors': true,
        'vertexShader': true
    }

}